### ISSUE TITLE
[Text improvement] Chapter 3: Differing arguments to find_package() call

### ISSUE THREAD

**Issue by gbiggs** [osrf/rosbook#18]
On page 42, the find_package() call arguments do not match what catkin generates for a Python node. It only adds rospy, not roscpp (since we are creating a Python-only package). Also std_msgs was not added earlier when the dependency was added to the package.xml file. This is confusing for the reader.

**Comment by gerkey** [comment]
I updated to use your version of the examples and updated the book text to include from there directly, to avoid disagreement. Fixed in reprint.

**Comment by gbiggs** [comment]
Do you want me to make a tag?
