### ISSUE TITLE
controllers.yaml with move_group and gazebo

### ISSUE THREAD

**Issue by SteveMacenski** [osrf/rosbook#2]
Hi!

For the cougarbot section, there is a yaml file you make with the controller_manager_ns: / etc... to interface the moveit config and gazebo, rviz. 

The format as it appears, it fails to work in the gazebo cougarbot launch file. To make it work, the controller_list: line must be deleted and the rest one indent less. Otherwise, an error about not loading the arm_controller into the namespace or that it doesn't exist. 

> Could not load controller 'arm_controller' because the type was not specified. Did you load the controller configuration on the parameter server (namespace: '/arm_controller')?
> [ERROR] [WallTime: 1452296250.613456] [2.923000] Failed to load arm_controller

Further, when you try to open move_group.launch it complains that there is no controller_list. 

> MoveitSimpleControllerManager: No controller_list specified.

These seem to be mutually unworkable. 

I am in ROS indigo

**Comment by gerkey** [comment]
Thanks for the report; we're looking into it.

**Comment by SteveMacenski** [comment]
I figured out the issue last night. I assumed that the book mistakenly did not change the launch files to the new controllers.yaml file used in the moveit_config. It seems that the controllers.yaml for moveit_config and in the gazebo launch files are different. I assume the gazebo launch file one creates the actual controllers and the moveit_config controllers are just connecting them? Or are there 2 controllers running separately?

**Comment by gerkey** [comment]
Fixed in the reprint.
