### ISSUE TITLE
[Text improvement] Chapter 4: Confusing description of Python modules

### ISSUE THREAD

**Issue by gbiggs** [osrf/rosbook#20]
The wording in paragraph 3 on page 55 could confuse the reader into thinking there is a file called "basics.srv", due to the collision between the generated .srv submodule of the (ROS) package module and the .srv extension for service definition files. The wording could be improved, particularly by not calling the submodule an extension, but also by just calling it what it is (a services-containing submodule of the basics Python package?).

**Comment by gerkey** [comment]
Fixed in reprint.
