### ISSUE TITLE
[Text improvement] Chapter 4: Move description of using rosservice

### ISSUE THREAD

**Issue by gbiggs** [osrf/rosbook#21]
The description of using rosservice call on page 57 could be moved to the "checking that everything works" section (on page 56) and referenced from here as "We previously used rosservice to call the service. This is the simplest way to use a service." This would make the "checking" section include actually checking that the service works, and not just that it exists. Particularly as the next section after the "checking" section changes the node source code.

**Comment by gerkey** [comment]
Fixed in reprint.
