### ISSUE TITLE
chapter 12 codes freezing

### ISSUE THREAD

**Issue by JafarAbdi** [osrf/rosbook#29]
When I run the codes in followbot package the window doesn't show up and freeze, but when I comment cv2.namedWindow("window", 1) line as in this link :: http://answers.ros.org/question/257440/python-opencv-namedwindow-and-imshow-freeze/
 it works this's happening when I run any node in followbot package

**Comment by rpfly3** [comment]
@JafarAbdi I also found this problem. Commenting out line is my solution as well.
