### ISSUE TITLE
Laser plug-in publishes abnormal scan results.

### ISSUE THREAD

**Issue by kishorekumar29** [osrf/rosbook#3]
I have added the laser plug-in to my URDF file and launched the model successfully in gazebo. when i tried to visualize the behavior of laser plug-in in rviz after the doing the basic settings as instructed, i couldn't find any results. I read the topic using the command "rostopic echo /scan" and obtained the result below
![topic](https://cloud.githubusercontent.com/assets/7499196/12449364/bddd0b9c-bfa2-11e5-928c-14b71bbc1d99.png)

Below is my URDF file:

       <?xml	version="1.0"?>
       <robot
       name="JMbot1.1">
        <link
         name="Base_plate">
         <inertial>
         <origin
         xyz="9.28103095721513E-18 -0.00236910483921667 1.69476737537172E-19"
          rpy="0 0 0" />
       <mass
        value="0.553781193313651" />
      <inertia
        ixx="0.00613802647719325"
        ixy="-5.56633892187664E-20"
        ixz="1.95355359086701E-19"
        iyy="0.0102825986842358"
        iyz="3.22575373206078E-19"
        izz="0.00414996381570526" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://jmbot1_description/meshes/Base_plate.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.749019607843137 0.749019607843137 0.749019607843137 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://jmbot1_description/meshes/Base_plate.STL" />
      </geometry>
    </collision>
          </link>
         <link
          name="Wheel_R">
           <inertial>
            <origin
        xyz="-0.0394771489417549 -5.20417042793042E-18 1.73472347597681E-18"
        rpy="0 0 0" />
      <mass
        value="0.450643534719172" />
      <inertia
        ixx="0.000916081598048295"
        ixy="1.48930401404157E-20"
        ixz="-9.81573335914851E-21"
        iyy="0.000533948766711724"
        iyz="0"
        izz="0.000533948766711724" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://jmbot1_description/meshes/Wheel_R.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.749019607843137 0.749019607843137 0.749019607843137 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://jmbot1_description/meshes/Wheel_R.STL" />
      </geometry>
    </collision>
       </link>
     <joint  name="Wheel_R"
      type="continuous">
    <origin
      xyz="0.135 0.015 0"
      rpy="1.4389236251236 -2.11732407237853E-18 3.14159265358979" />
    <parent
      link="Base_plate" />
    <child
      link="Wheel_R" />
    <axis
      xyz="1 0 0" />
       </joint>
      <link
    name="Wheel_L">
    <inertial>
      <origin
        xyz="-0.0394771489417549 1.21430643318377E-17 8.67361737988404E-18"
        rpy="0 0 0" />
      <mass
        value="0.450643534719172" />
      <inertia
        ixx="0.000916081598048295"
        ixy="2.90916462871053E-20"
        ixz="-2.96782618561828E-20"
        iyy="0.000533948766711724"
        iyz="5.42101086242752E-20"
        izz="0.000533948766711724" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://jmbot1_description/meshes/Wheel_L.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.749019607843137 0.749019607843137 0.749019607843137 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://jmbot1_description/meshes/Wheel_L.STL" />
      </geometry>
    </collision>
       </link>
       <joint
      name="Wheel_L"
      type="continuous">
    <origin
      xyz="-0.135 0.015 0"
      rpy="0.928716950811488 0 0" />
    <parent
      link="Base_plate" />
    <child
      link="Wheel_L" />
    <axis
      xyz="-1 0 0" />
     </joint>
     <link
    name="Castor_F">
    <inertial>
      <origin
        xyz="-4.16333634234434E-17 0 0.03116425205832"
        rpy="0 0 0" />
      <mass
        value="0.0565552012132997" />
      <inertia
        ixx="2.44755054701354E-05"
        ixy="-6.23799465703127E-37"
        ixz="-1.01877548447475E-20"
        iyy="2.44755054701354E-05"
        iyz="8.40860868946448E-21"
        izz="7.43413937311511E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://jmbot1_description/meshes/Castor_F.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://jmbot1_description/meshes/Castor_F.STL" />
      </geometry>
    </collision>
       </link>
       <joint
    name="Castor_F"
    type="continuous">
    <origin
      xyz="0 0 0.15"
      rpy="-1.5707963267949 -0.957338804063555 8.69652688200404E-17" />
    <parent
      link="Base_plate" />
    <child
      link="Castor_F" />
    <axis
      xyz="0 0 1" />
        </joint>
       <link
    name="Castor_R">
    <inertial>
      <origin
        xyz="0 -1.11022302462516E-16 0.0311642520583196"
        rpy="0 0 0" />
      <mass
        value="0.0565552012132997" />
      <inertia
        ixx="2.44755054701354E-05"
        ixy="-1.69406589450864E-21"
        ixz="-3.77743078318297E-20"
        iyy="2.44755054701354E-05"
        iyz="2.51661046244309E-22"
        izz="7.43413937311511E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://jmbot1_description/meshes/Castor_R.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://jmbot1_description/meshes/Castor_R.STL" />
      </geometry>
    </collision>
       </link>
     <joint
    name="Castor_R"
    type="continuous">
    <origin
      xyz="0 0 -0.15"
      rpy="1.5707963267949 -0.931442561406784 3.14159265358979" />
    <parent
      link="Base_plate" />
    <child
      link="Castor_R" />
    <axis
      xyz="0 0 1" />
     </joint>

     <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </visual>
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
         </link>
          <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 -0.055 0.2" rpy="0 0 0"/>
    <parent link="Base_plate"/>
    <child link="hokuyo_link"/>
      </joint>

       <gazebo>
     <plugin	name="differential_drive_controller"
  	filename="libgazebo_ros_diff_drive.so">
	<leftJoint>Wheel_L</leftJoint>	
	<rightJoint>Wheel_R</rightJoint>
	<robotBaseFrame>Base_plate</robotBaseFrame>
	<wheelSeparation>0.235</wheelSeparation>
	<wheelDiameter>0.12</wheelDiameter>
	<publishWheelJointState>true</publishWheelJointState>
	</plugin>
      </gazebo>
       <gazebo>
       <plugin	name="joint_state_publisher"
	filename="libgazebo_ros_joint_state_publisher.so">
  	<jointName>Castor_F, Castor_R</jointName>
	</plugin>	
        </gazebo>

      <gazebo reference="hokuyo_link">
    <sensor type="gpu_ray" name="hokuyo">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>100</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <plugin name="laser" filename="libgazebo_ros_gpu_laser.so">
        <topicName>/scan</topicName>
        <frameName>hokuyo_link</frameName>
           </plugin>
             </sensor>
             </gazebo>

        </robot>

**Comment by gerkey** [comment]
Thanks for the report; we're looking into it.

**Comment by gerkey** [comment]
It's hard how the robot is intended to work without having access to your meshes, but it looks like your laser is mounted in an unusual orientation. Did you intend for it to be horizontal (as is common for navigation)?

You might try this modification to the `hokuyo_joint`:

~~~
<joint name="hokuyo_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="0.0 -0.055 0.2" rpy="1.5708 -1.5708 0"/>
  <parent link="Base_plate"/>
  <child link="hokuyo_link"/>
</joint>
~~~

**Comment by kishorekumar29** [comment]
Thank you, The issue still persists even after the above changes. I found the actual problem, its i am using unsupportedd graphics driver. Using a non GPU sensor plugin solved the issue.

**Comment by gerkey** [comment]
Ah, that would explain it. But the behavior in that situation is not great. You should get some sort of obvious error instead of seeing bogus data. If you look through the console output from launching the system, does Gazebo complain about the unsupported GPU?

We might consider opening an issue with Gazebo to force a more obvious error (maybe even a fatal error) in this situation.

**Comment by kishorekumar29** [comment]
Modifying the URDF to right hand coordinate system fixed the issue.
